options:
  service-url:
    type: string
    description: "The URL of the service."
    default: ""
  repository-origin:
    type: string
    description: "The value of the 'Origin' field of the repository."
    default: "Ubuntu"
  repository-version:
    type: string
    description: "The value of the 'Version' field of the repository."
    default: ""
  mirror-uri:
    type: string
    description: |
      The URI of the repository to mirror.
      The format is the following:

      http[s]://[<user>:<pass>@]<hostname>/<path> <suite> <components>
    default: ""
  mirror-archs:
    type: string
    description: "A space-separated list of architectures to mirror."
    default: "source i386 amd64"
  mirror-gpg-key:
    type: string
    description: "GPG key for the repository to mirror."
    default: ""
  sign-gpg-key:
    type: string
    description: "GPG key for signing the archive."
    default: ""
  sign-gpg-passphrase:
    type: string
    description: "Passphrase for the sign-gpg-key."
    default: ""
  auth-cache-time:
    type: string
    description: |
      Caching time for positive auth responses.

      This key is only considered when the application is related to
      basic-auth-service, which provides external authorization.

      The value can contain suffixes like "m" or "h" (e.g. "5m").
    default: ""
